# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-prettyprint
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.PrettyPrint
  dependencies:
  - base >= 4.7 && < 5
  - deepseq
  - txs-language
  - txs-name
  - txs-sort
  #- txs-valexpr

ghc-options:
- -O
- -Werror
- -Wall
- -Widentities
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
