# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

name: txs-cli
version: 0.1.0.0
github: "TorXakis/TorXakis"
license: BSD3
author:
- "Kerem Ispirli"
maintainer:
- "kerem.ispirli@tno.nl"
copyright: "Copyright: (c) 2018 TorXakis"

extra-source-files:
- README.md
- license.txt

synopsis: TorXakis CLI that uses the web server as backend.

default-extensions:
# - DataKinds
# - TypeOperators

dependencies:
- base >= 4.7 && < 5
  
ghc-options:
- -O2
- -optc-O3
- -Werror
- -Wall

library:
  source-dirs: src
  exposed-modules:
  - CLI
  - Env
  dependencies:
  - aeson
  - async
  - base
  - bytestring
  - filepath
  - haskeline
  - microlens
  - mtl
  - safe-exceptions
  - text
  - wreq

executables:
  txs-cli-exe:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - base
    - bytestring
    - microlens-aeson
    - microlens
    - mtl
    - process
    - wreq

    - txs-cli

tests:
  txs-cli-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    # - aeson
    # - bytestring
    # - microlens-aeson
    # - microlens
