# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-funcsignature
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.ContextFuncSignature
  - TorXakis.FuncSignature
  - TorXakis.FuncSignatureContext
  dependencies:
  - base >= 4.7 && < 5
  - containers
  - deepseq
  - hashable
  - hashmap
  - txs-basics
  - txs-sort
  - txs-name
  - Unique


ghc-options:
- -O
- -Werror
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wredundant-constraints
- -Wincomplete-uni-patterns
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
