# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

engines:
  fixme:
    enabled: true
  hlint:
    enabled: true

ratings:
  paths:
  - "**.hs"
