# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
selected-solver: "z3"
available-solvers:
- solver-id: "z3"
  executable-name: "z3"
  flags:
  - "-smt2"
  - "-in"
- solver-id: "z3str3"
  executable-name: "z3"
  flags:
  - "-smt2"
  - "-in"
  - "smt.string_solver=z3str3"
- solver-id: "cvc4"
  executable-name: "cvc4"
  flags:
  - "--lang=smt"
  - "--incremental"
  - "--strings-exp"
  - "--fmf-fun-rlv"
  - "--uf-ss-fair"
  - "--no-strings-std-ascii"
parameters:
- name: "ImpRel"
  value: "IOCO"       # IOCO
- name: "IncrementChoice_IntPower"
  value: "4"         # > 0
- name: "IncrementChoice_IntRange"
  value: "65536"       # > 0
- name: "IncrementChoice_MaxGeneratedStringLength"
  value: "10"       # > 0
- name: "InputCompletion"
  value: "ANGELIC"       # ANGELIC
- name: "RandSolve_IntHalf"
  value: "1000"          # > 0
- name: "RandSolve_IntNum"
  value: "5"         # > 0
- name: "RandSolve_adtWidth"
  value: "5"         # > 0
- name: "Randomization"
  value: "IncrementChoice" # No | Partition | TrueBins | IncrementChoice
- name: "Sim_inputEager"
  value: "0"       # 0-3
- name: "Test_inputEager"
  value: "3"       # 0-3
- name: "TrueBins_Next"
  value: "Linear"       # Linear |Power | Exponent
- name: "TrueBins_NrOfBins"
  value: "10"       # > 0
- name: "TrueBins_StringLength"
  value: "6"       # > 0
- name: "TrueBins_StringMode"
  value: "Regex"   # Length | Regex
- name: "max_rand_depth"
  value: "4"       # > 0
- name: "Sim_deltaTime"
  value: "200"        # > 0
- name: "Sut_deltaTime"
  value: "2000"       # > 0
- name: "Sut_ioTime"
  value: "10"       # > 0
