selected-solver: "cvc4"
available-solvers:
- solver:
    id: "z3"
    executable-name: "z3"
    flags:
    - "smt2"
    - "-in"
- solver:
    id: "z3str3"
    executable-name: "z3"
    flags:
    - "smt2"
    - "-in"
    - "smt.string_solver=z3str3"
- solver:
    id: "cvc4"
    executable-name: "cvc4-2017-06-13-win32-opt"
    flags:
    - "--lang=smt"
    - "--incremental"
    - "--foo=bar"
