# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

resolver: lts-11.22
ghc-variant: integersimple

packages:
- sys/behave
- sys/behavedefs
- sys/behaveenv
- sys/bexpr
- sys/cnect
- sys/core
- sys/coreenv
- sys/defs
- sys/lexregexxsd
- sys/lpe
- sys/server
- sys/serverenv
- sys/solve
- sys/testsel
- sys/ui
- sys/value
- sys/valexpr
- sys/txs-compiler

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- git: https://github.com/TorXakis/text-via-sockets.git
  commit: e3228cd0407ec0d7991a544e154ea2def184fcae

# Override default flag values for local packages and extra-deps
flags:
  text:
    integer-simple: true
  hexpat:
    bundle: true
  hashable:
    integer-gmp: false
  integer-logarithms:
    integer-gmp: false
  scientific:
    integer-simple: true

# Extra package databases containing global packages
extra-package-dbs:

# Override the architecture used by stack, especially useful on Windows
# arch: i386
arch: x86_64
