# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

resolver: lts-11.17
ghc-variant: integersimple

packages:
- location: sys/behave
- location: sys/behavedefs
- location: sys/behaveenv
- location: sys/bexpr
- location: sys/cnect
- location: sys/core
- location: sys/coreenv
- location: sys/defs
- location: sys/lexregexxsd
- location: sys/lpe
- location: sys/server
- location: sys/serverenv
- location: sys/solve
- location: sys/testsel
- location: sys/ui
- location: sys/value
- location: sys/valexpr
- location: sys/txs-compiler

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- git: https://github.com/TorXakis/text-via-sockets.git
  commit: e3228cd0407ec0d7991a544e154ea2def184fcae

# Override default flag values for local packages and extra-deps
flags:
  text:
    integer-simple: true
  hexpat:
    bundle: true
  hashable:
    integer-gmp: false
  integer-logarithms:
    integer-gmp: false
  scientific:
    integer-simple: true

# Extra package databases containing global packages
extra-package-dbs:

# Override the architecture used by stack, especially useful on Windows
# arch: i386
arch: x86_64
