git remote remove origin;
git remote add origin https://github.com/TorXakis/TorXakis.git;
git fetch;
git checkout gh-pages;
git rebase $TRAVIS_BRANCH;
cp -a /home/travis/build/TorXakis/TorXakis/.stack-work/install/x86_64-linux/lts-8.13/8.0.2/doc/all/. ./doc/;
git add .;
commitMsg="Haddock @ $(date +%Y%m%d_%H%M%S)";
git commit -m "$(echo $commitMsg)";
git push -f "https://keremispirli:$GITHUB_TOKEN@github.com/TorXakis/TorXakis.git";