# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

name: txs-lib
version: 0.1.0.0
github: "TorXakis/TorXakis"
license: BSD3
author:
- "Damian Nadales"
maintainer:
- "damian.nadales@gmail.com"
copyright: "Copyright: (c) 2017 TNO"

extra-source-files:
- README.md
- ChangeLog.md
- license.txt

synopsis: Interface to the `TorXakis` parser and core.
maintainer:
- "damian.nadales@gmail.com"

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
  
ghc-options:
- -O2
- -optc-O3
- -Werror
- -Wall
- -optc-ffast-math

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.Lib
  - TorXakis.Lib.Examples
  - TorXakis.Session
  dependencies:
  - text
  - path
  - stm
  - deepseq
  - microlens
  - mtl
  - stm-chans  
  - stm-conduit
  - conduit
  - conduit-combinators
  - async
  # `TorXakis` dependencies.
  - defs
  - valexpr
  - front
  - core
  - coreenv
  - txs-lenses

tests:
  txs-lib-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -O
    dependencies:
    - hspec
    - txs-lib
