# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

name: txs-lib
version: 0.1.0.0
github: "TorXakis/TorXakis"
license: BSD3
author:
- "Damian Nadales"
maintainer:
- "damian.nadales@gmail.com"
copyright: "Copyright: (c) 2017 TNO"

extra-source-files:
- README.md
- license.txt

synopsis: Interface to the `TorXakis` parser and core.
maintainer:
- "damian.nadales@gmail.com"

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- filepath
  
ghc-options:
- -O2
- -optc-O3
#- -Werror
- -Wall
- -optc-ffast-math

library:
  source-dirs: src
  dependencies:
  - aeson
  - async
  - bytestring
  - conduit
  - conduit-combinators
  - containers
  - deepseq
  - directory
  - extra
  - http-client
  - lens-aeson
  - microlens
  - microlens-th  
  - mtl
  - network
  - optparse-applicative
  - path
  - process
  - random
  - stm
  - stm-chans  
  - stm-conduit
  - text
  - text-via-sockets
  - time
  - transformers
  - wreq
  - yaml
  - MissingH
  # `TorXakis` dependencies.
  - behaveenv
  - bexpr
  - core
  - coreenv
  - defs
  - txs-compiler
  - txs-lenses
  - valexpr
  - value

tests:
  txs-lib-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -O
    dependencies:
    - hspec
    - txs-lib
    - defs
