#!/bin/bash

# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

# Install TorXakis.

apt-get update

echo "Installing ${TXS_PKG}"

cd /build

apt-get install $TXS_PKG -y

cd /TorXakis

# # Test with "Echo".
cat test/examps/Echo/Echo_Simulator.txscmd | torxakis examps/Echo/Echo.txs &> /dev/null &
cat test/examps/Echo/Echo_Tester.txscmd | torxakis examps/Echo/Echo.txs

# # Test with "Moving Arms"
cat test/examps/MovingArms/MovingArms_Simulator.txscmd | \
    torxakis examps/MovingArms/MovingArms.txs examps/MovingArms/RestrictedAxisPurpose.txs \
    &> /dev/null &
cat test/examps/MovingArms/MovingArms_RestrictedAxisPurpose_eager3_Tester.txscmd | \
    torxakis examps/MovingArms/MovingArms.txs  examps/MovingArms/RestrictedAxisPurpose.txs
