#!/bin/bash

# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

# Create a TorXakis package.

# NOTE: this script will build TorXakis and download the SMT solvers, so it is
# not ready to be incorporated in CI yet. Since `fpm` and `github-release` are
# additional packages that need to be installed, doing it in the current CI
# will slow down the process. It would therefore make more sense to go to
# containerized CI for TorXakis, which includes all the needed dependencies.

if [ "$#" -ne 1 ]; then
    echo "Missing TorXakis version"
fi

for ubuntu_dirs in `ls -d ci/mk-package/ubuntu/*/`
do
    ubuntu_version=`basename ${ubuntu_dirs}`
    docker run --rm \
           -e TXS_VERSION=$1 \
           -e UBUNTU_VERSION=${ubuntu_version} \
           -v $(pwd)/.package-build:/build \
           -ti torxakis-packager:${ubuntu_version} mk-package.sh

done
