#!/bin/bash

# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

# Build the docker containers

mkdir -p ci/mk-package/.package-build

for ubuntu_dirs in `ls -d ci/mk-package/ubuntu/*/`
do
    ubuntu_version=`basename ${ubuntu_dirs}`
    docker build \
           --tag=torxakis-packager:${ubuntu_version} \
           -f ci/mk-package/ubuntu/${ubuntu_version}/Dockerfile \
           ci/mk-package
done
