name: sort
version: 0.1.0.0
github: "TorXakis/TorXakis"
license: BSD3
author:
  - "Pierre van de Laar"
  - "Kerem Ispirli"
maintainer:
  - "pierre.vandelaar@tno.nl"
  - "kerem.ispirli@tno.nl"
copyright:      "Copyright: (c) 2017-2018 TNO"

# Metadata used when publishing your package
synopsis: Sorts for TorXakis
category: Language

description: Please see the README on Github at <https://github.com/TorXakis/TorXakis#readme>

# Shared dependencies across library, benchmarks, and tests.
dependencies:
- base >= 4.7 && < 5
- containers
- deepseq
- hashable
- text
- Unique
- unordered-containers

default-extensions:
- OverloadedStrings
- DeriveGeneric

ghc-options:
  - -O2
  - -optc-O3
  - -Werror
  - -Wall
  - -optc-ffast-math

library:
  source-dirs: src
  exposed-modules:
  - Id
  - Name
  - Sort
  - SortOf
  dependencies:

tests:
  sort-test:
    main: TestMain.hs
    source-dirs:
    - src # TODO: We have to use the X.Internal convention to avoid having to
          # recompile the sources in our tests!
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sort
    - HUnit
