# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-lex-regex-xsd
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"



library:
  source-dirs: src
  exposed-modules:
  - TorXakis.RegexAlex
  build-tools:
  - alex
  dependencies:
  - array
  - base >= 4.7 && < 5
  - text

extra-source-files:
- README.md

ghc-options:
- -Werror
- -Wall
- -O
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wredundant-constraints
#- -Wincomplete-uni-patterns  -- for alex
#- -Wmissing-local-signatures -- for alex
#- -Wmonomorphism-restriction -- for alex
