# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-smt
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- hashmap
- mtl
- process
- text

- txs-basics
- txs-name
- txs-solve
- txs-sort
- txs-valexpr
- txs-value
- txs-var

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.SmtM
  dependencies:
  - array # for Happy
  - bimap
  - containers
  - deepseq
  - hashable
  - MissingH
  - regex-tdfa
  - time
  
  - txs-regex
  build-tools:
  - alex
  - happy

tests:
    txs-smt-test:
        main : TestMain.hs
        source-dirs: test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - HUnit
        - txs-smt
        - txs-symbolic

ghc-options:
- -O
- -fno-ignore-asserts       # must be after -O otherwise optimization turns asserts off again
#- -Werror
- -Wall
- -Widentities
#- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmissing-home-modules
#- -Wmissing-local-signatures
#- -Wmonomorphism-restriction
- -Wredundant-constraints
