# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-sort-gen
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- txs-name
- txs-sort

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.ContextTestSort
  - TorXakis.GenCollection
  - TorXakis.SortGen
  - TorXakis.SortGenContext
  - TorXakis.TestSortContext
  - TorXakis.TestSortData
  dependencies:
    - containers
    - hashmap
    - multimap
    - txs-basics
    - txs-language
    - txs-name-gen

tests:
    txs-sort-gen-test:
        main : Spec.hs
        source-dirs: test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - hspec
        - text
        - txs-sort-gen

ghc-options:
- -O
- -Werror
- -Wall
- -Widentities
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints

