name:                txs-compiler
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Damian Nadales"
maintainer:          "damian.nadales@gmail.com"
copyright:           "Copyright: (c) 2017 Damian Nadales"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Werror
- -Wall
- -O
- -fconstraint-solver-iterations=10

library:
  source-dirs: src
  dependencies:
  - text
  - parsec
  - mtl
  - containers
  - transformers
  - unordered-containers
  - MissingH
  - ilist
  - lens
  - Unique
  # TorXakis dependencies
  - defs
  - valexpr
  - behave
  - bexpr
  
tests:
  txs-compiler-test:
    main: Spec.hs
    source-dirs:
    - test

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -O
    dependencies:
    - hspec
    - filemanip
    - filepath
    - containers    
    # TorXakis dependencies
    - front # Temporary dependencies till the whole front is replaced.
    - defs
    - valexpr

    # Local dependencies
    - txs-compiler

extra-source-files:
- test/data/success/*.txs
- test/data/examps/*.txs
- test/data/parser/success/*.txs

