# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-server
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- text

executable:
  source-dirs: src
  main: TorXakis.Server
  dependencies:
  - containers
  - mtl
  - network
  - optparse-applicative
  - txs-core
  - txs-corestate
  - txs-language
  - txs-serverstate
  - txs-valexpr
  - txs-var

ghc-options:
- -O
- -Werror
- -Wall
- -Widentities
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
