# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-basics-gen
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- text
- txs-basics

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.Cover
  - TorXakis.ErrorGen
  - TorXakis.NameGen
  dependencies:
  - base >= 4.7 && < 5
  - deepseq

extra-source-files:
- README.md

ghc-options:
- -Werror
- -Wall
- -O
- -Widentities
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints

tests:
    txs-basics-gen-test:
        main : Spec.hs
        source-dirs: test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - containers
        - hspec
        - txs-basics-gen