# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-value
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- text
- txs-sort

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.Value
  build-tools:
  - alex
  - happy
  dependencies:
  - array
  - bytestring
  - containers
  - deepseq
  - hexpat
  - regex-tdfa
  - txs-basics
  - txs-name

tests:
    txs-value-test:
        main : Spec.hs
        source-dirs: test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - txs-smt

ghc-options:
- -Werror
- -Wall
- -O
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wredundant-constraints
#- -Wincomplete-uni-patterns  -- for alex
#- -Wmissing-local-signatures -- for alex
#- -Wmonomorphism-restriction -- for alex
