# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-valexpr-gen
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- txs-name
- txs-sort
- txs-valexpr
- txs-value

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.TestValExprContext
  dependencies:
    - hashmap
    - text
    - txs-basics
    - txs-sort-gen
    - txs-value-gen
    - txs-var
    - txs-var-gen
    - txs-funcsignature-gen

tests:
    txs-valexpr-gen-test:
        main : Spec.hs
        source-dirs: test
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - hspec
        - text
        - txs-var
        - txs-valexpr-gen

ghc-options:
- -Werror
- -Wall
- -O
- -Widentities
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
