# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.
name:                txs-bexpr
version:             0.1.0.0
github:              "TorXakis/TorXakis"
license:             BSD3
author:              "Pierre van de Laar"
maintainer:          "pierre.vandelaar@tno.nl"
copyright:           "Copyright (c) 2015-2017 TNO and Radboud University"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - TorXakis.BExpr
  - TorXakis.ProcDef
  - TorXakis.ProcSignature
  dependencies:
  - containers
  - deepseq
  - hashable
  - hashmap
  - text
  - Unique
  # TorXakis dependencies
  - txs-basics
  - txs-chan
  - txs-name
  - txs-sort
  - txs-valexpr
  - txs-value
  - txs-var
  
ghc-options:
- -O
- -Werror
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
