# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

name: torxakis # you probably want to 'snapcraft register <name>'
version: 'nightly' # just for humans, typically '1.2+git' or '1.3.2'
summary: A tool for testing systems using a model-based approach. # 79 char long summary
description: |
  TorXakis allows to test systems by writing models in a process algebraic
  fashion. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots

parts:  
  torxakis-bin:
    # See 'snapcraft plugins'
    plugin: dump
    source: .stack-work/install/x86_64-linux-nopie/lts-9.7/8.0.2/bin/
    stage-packages: []

  torxakis-bootstrap-data:
    # Bootstrap data for TorXakis, for instance initial configuration.
    #
    # This makes the `snap/data` folder available, and data can be copied upon
    # starting `TorXakis`, for instance, as follows:
    #
    # cp $SNAP/snap/data/* $SNAP_USER_DATA/
    #
    # See: https://forum.snapcraft.io/t/use-of-home-and-network-plugs/2587/19
    plugin: dump
    source: snap/data
    
  cvc4-bin:
    plugin: dump
    source: https://github.com/TorXakis/Dependencies/releases/download/cvc4_1.5/cvc4-1.5-x86_64-linux-opt.tar.gz

  z3-bin:
    plugin: dump
    source: https://github.com/TorXakis/Dependencies/releases/download/z3-4.5.1/z3-4.5.1.x64-ubuntu-14.04.tar.gz
    
apps:
  txsui:
    command: txsui
    plugs:
      - network
      - home
      - network-bind

  txsserver:
    command: txsserver
    plugs: 
      - network
      - home
      - network-bind

  z3:
    command: bin/z3
    plugs:
      - network
      - home
      - network-bind

  cvc4:
    command: cvc4-1.5-x86_64-linux-opt
    plugs:
      - network
      - home
      - network-bind
      
